spring:
  application:
    name: ecommerce

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ecommerce?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: mymysql1645

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
